### ISSUE TITLE
调试出错

### ISSUE THREAD

**Issue by lisanyao** [Clansty/superstar-checkin#16]
[2022-04-29T00:08:35.094] [ERROR] [Android:1265744892] - failed to send: [Group: NaN] 
undefined(1)
Waiting for the debugger to disconnect...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<ApiRejection>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

提示错误代码：
const info = (...message) => {
    console.info(`[${date()}][INFO]`, ...message);
};

**Comment by clansty** [comment]
> [Group: NaN]

你是不是没有设置接收提醒的群

**Comment by lisanyao** [comment]
作者大大，已配置，还是同样的问题
（定位签到，不使用，有关定位签到部分没有配置，应该没有影响吧？）

**Comment by clansty** [comment]
不使用你也得给它一个空数组

**Comment by lisanyao** [comment]
谢谢作者大大，成功了
