### ISSUE TITLE
实例化配置文件的时候应该做检查

### ISSUE THREAD

**Issue by Zxilly** [Clansty/superstar-checkin#17]
https://github.com/Clansty/superstar-checkin/blob/338e32fc5f91c33c00a26fc21e87d609c1639c11/providers/config.ts#L19
直接as过来会导致不可预料的运行时错误

**Comment by clansty** [comment]
就 我预期中配置文件都是正确的，没有考虑过会有错误的配置文件。如果配置文件错误的话，用户应该也能发现
