### ISSUE TITLE
获取Cookie时出错

### ISSUE THREAD

**Issue by DangerFickle** [Clansty/superstar-checkin#21]
![image](https://user-images.githubusercontent.com/59493932/170411524-028ba26d-6f89-4dec-873e-ad2ff005d0ba.png)

**Comment by Morikernel** [comment]
阿里的腾讯服务器问题

**Comment by DangerFickle** [comment]
> 阿里的腾讯服务器问题

我在项目根目录下创建data文件夹，data内创建superstar-data.json文件就能正常运行了

**Comment by Sunshine214000** [comment]
这个json文件是本地创建生成的把

**Comment by Morikernel** [comment]
> > 阿里的腾讯服务器问题
> 
> 我在项目根目录下创建data文件夹，data内创建superstar-data.json文件就能正常运行了

这个json文件是本地创建生成的把

**Comment by DangerFickle** [comment]
> > > 阿里的腾讯服务器问题
> > 
> > 
> > 我在项目根目录下创建data文件夹，data内创建superstar-data.json文件就能正常运行了
> 
> 这个json文件是本地创建生成的把

我这里没有自动生成
