### ISSUE TITLE
这里的代码好像有些问题，一直提示错误

### ISSUE THREAD

**Issue by kobeninya** [Clansty/superstar-checkin#24]
![Screenshot_2022-06-03-16-01-21-26_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://user-images.githubusercontent.com/101168817/171837102-e9e25955-c3a8-4583-b7d8-6a2e9c33741f.jpg)

**Comment by moeshin** [comment]
没错误日志吗。。

**Comment by kobeninya** [comment]
我试了试把那个链接后面加？uname=...&code=就对了

MoeShin ***@***.***> 于 2022年6月3日周五 22:18写道：

**Comment by moeshin** [comment]
代码被你改过了吧，右边的单引号都不见了

https://github.com/Clansty/superstar-checkin/blob/bb393292ddebf8101ec90d0194ca35110706b652/requests/login.ts#L12-L23

你把那个单引号改成问号了。。

**Comment by kobeninya** [comment]
我是正常运行出现错误才在那里改的，那个，问号，单引号，只是改代码时没改完，没注意截图。
MoeShin ***@***.***> 于 2022年6月4日周六 21:18写道：
