### ISSUE TITLE
请问如何更换QQ的登陆协议？

### ISSUE THREAD

**Issue by DangerFickle** [Clansty/superstar-checkin#25]
请问如何更换QQ的登陆协议？

**Comment by clansty** [comment]
暂时大概没有做，可以去源码里面修改

**Comment by DangerFickle** [comment]
> 暂时大概没有做，可以去源码里面修改

具体在哪一个文件内呢

**Comment by clansty** [comment]
https://github.com/Clansty/superstar-checkin/blob/df1484d186a053dada3d78a460bc44a5243e5ce4/providers/bot.ts#L9-L11
