### ISSUE TITLE
位置签到貌似要把 `lat` 和 `lon` 的参数交换一下位置

### ISSUE THREAD

**Issue by Zxilly** [Clansty/superstar-checkin#28]
我测试出来是这样的

**Comment by Zxilly** [comment]
签到中携带位置信息的不用改，因为它本身就是反的

**Comment by clansty** [comment]
我代码里面应该是对的，因为 lat 就是 lat，lon 就是 lon，没有对应到中文。要翻译成中文的话，我也不知道哪个是哪个，自己也会搞反。发现反了改一下就好，反正文字是对的

**Comment by moeshin** [comment]
lon 经度，lat 纬度，坐标经纬度就 (lon, lat) 经度在前，搞反就跑到奇怪的地方上课了 :joy:

**Comment by Zxilly** [comment]
> lon 经度，lat 纬度，坐标经纬度就 (lon, lat) 经度在前，搞反就跑到奇怪的地方上课了 :joy:

学习通现在的处理逻辑经纬度是反的

**Comment by moeshin** [comment]
我测试没有反 QwQ

**Comment by moeshin** [comment]
https://github.com/Clansty/superstar-checkin/blob/bb393292ddebf8101ec90d0194ca35110706b652/config.example.yaml#L14-L15

配置写的注释是错的
