### ISSUE TITLE
非法请求

### ISSUE THREAD

**Issue by Morikernel** [Clansty/superstar-checkin#29]
非法请求，哥哥接口好像又GG了

**Comment by moeshin** [comment]
我试了没有问题

**Comment by Morikernel** [comment]
我这天天还是非法请求哈哈

**Comment by moeshin** [comment]
该不会代码没更新、更新没编译或者 IP 被搬了吧 😂

不行的换成其他接口康康 https://github.com/moeshin/cx-auto-sign/issues/28#issuecomment-1139710861

**Comment by clansty** [comment]
22/9/7 测试没问题
