### ISSUE TITLE
QQ登录时获取滑动验证ticket后输入无反应

### ISSUE THREAD

**Issue by DangerFickle** [Clansty/superstar-checkin#32]
![image](https://user-images.githubusercontent.com/59493932/174861192-6151d827-69f4-4edc-ae89-748cbfb0aff6.png)

**Comment by clansty** [comment]
这个没有做，需要使用其他支持的 基于 oicq 的程序（比如 [Icalingua++](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus)）登录一遍，这个帐号就通过验证了
