### ISSUE TITLE
docker 运行失败

### ISSUE THREAD

**Issue by kobeninya** [Clansty/superstar-checkin#33]
![image](https://user-images.githubusercontent.com/101168817/187121927-dc0a69a8-da2d-4306-bf48-8b2925a69799.png)

**Comment by clansty** [comment]
你的 docker 是不是很老

**Comment by clansty** [comment]
有构建好的镜像的

**Comment by kobeninya** [comment]
'https://passport2-api.chaoxing.com/v11/loginregister?‘,
        queryString.stringify({
            uname: account,
            code: password,

这里的queryString.stringify  新版本node好像不支持了

**Comment by clansty** [comment]
我这里好好的，docker 镜像肯定也能用
