### ISSUE TITLE
oicq的依赖装不上

### ISSUE THREAD

**Issue by DangerFickle** [Clansty/superstar-checkin#37]
![image](https://user-images.githubusercontent.com/59493932/190561546-9a69294c-f449-41d5-93c4-9112a7afd3fc.png)
![image](https://user-images.githubusercontent.com/59493932/190561575-ebf30e50-eb2d-4a6c-9488-1e54804246b4.png)

**Comment by clansty** [comment]
看看你服务器到 github 的连接

**Comment by DangerFickle** [comment]
本地开了科学也yarn install不上
