### ISSUE TITLE
定位失败！！！

### ISSUE THREAD

**Issue by XmchxUp** [Clansty/superstar-checkin#5]
用[此项目](https://github.com/mkdir700/chaoxing_auto_sign) 一模一样的经纬度，可以成功。
而这里签到不成功，测试了不下6次，求修复。

**Comment by clansty** [comment]
请附上你的配置文件和输出信息

**Comment by XmchxUp** [comment]
我删掉了(改用上面的项目了)。。。
输出信息：前面配置成功消息，签到信息，签到开始，签到失败（定位失败）。
就是有关定位的，我配置了好几个位置信息都不行。
