### ISSUE TITLE
这是什么原因

### ISSUE THREAD

**Issue by Morikernel** [Clansty/superstar-checkin#6]
![image](https://user-images.githubusercontent.com/73744839/159104442-393bb531-fc41-4690-8a54-c42d22bbe24c.png)

**Comment by chitsanfei** [comment]
手动创建一个data文件夹试一试

**Comment by Morikernel** [comment]
谢谢哥哥，果然就好啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Clansty/superstar-checkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Clansty/superstar-checkin] 这是什么原因 (Issue #6)





 
手动创建一个data文件夹试一试
